library(Signac)
library(Seurat)
library(tidyverse)
library(Matrix)
library(glue)
source('../preprocess_functions.R')
#python run_scbasset.py sample1_scATAC-seq_80k_processed.h5ad
get_celltype_TF_act <- function(df){
    cell_type_tf_act <- map_dfr(1:nrow(df),function(i){
        cell_type <-  df[i,1] %>% varhandle::unfactor() %>% as.character() 
        cell_type_top10 <- df[i,-1] |>  t() |> as.data.frame() %>% 
            rownames_to_column('gene') %>% slice_max(order_by = V1,n = 10) %>% 
            mutate(cell_types = cell_type) %>% 
            dplyr::select(cell_types,gene)
        return(cell_type_top10)
    },.progress = T)
    return(cell_type_tf_act)
}

sample_rds <- '../../data/Rds/ATAC/sample1_scATAC-seq_80k_processed.Rds'
#This generated by step 01
tf_activity_file <- '../../data/TF_activity/rawdata/sample1_scATAC-seq_80k_processed_tf_activity.txt.gz'
#This generated by step 03
rds <- readRDS(sample_rds)

TF_act_metadata <- rds@meta.data %>% rownames_to_column('cell_barcode')
TF_act <- data.table::fread(tf_activity_file)
TF_act_metadata <-
    left_join(TF_act_metadata,
              TF_act,
              by = c('cell_barcode' = 'V1')) %>%
    filter(!is.na(cell_type)) %>%
    group_by(cell_type) %>%
    summarise(across(where(is.numeric), sum)) %>%
    dplyr::select(c('cell_type', colnames(TF_act)[-1]))
tf_activity <- get_celltype_TF_act(TF_act_metadata)
data.table::fwrite(tf_activity, file = 'Sample1_tf_activity.xls',sep = '\t')



